### ISSUE TITLE
Create User Admin Panel

### ISSUE THREAD

**Issue by yeyo2k3** [AllianceBioversityCIAT/CLARISA-Legacy#21]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
As CLARISA admin user, I want manage CLARISA user for use platform and rest APIs so that we need a user admin panel to create or edit users

Add Screenshot
-------------------------------------------------------------------------------

Tasks:
-------------------------------------------------------------------------------
- [x] Migration
- [x] Backend 
- [x] Frontend

Deliverable or Expected outcome:
-------------------------------------------------------------------------------
- [x] Service
- [x] Admin Section
- [x] Change password Section
- [x] Roles Asign Section

Additional comments: 
-------------------------------------------------------------------------------

**Comment by yeyo2k3** [comment]
We created a section based on this [mockup ](https://docs.google.com/presentation/d/1Psmd2GaIit9YTsc-UvdV5dH3pmRPGzuBeGx7ZgZzRVc/edit?usp=sharing), Also we add some functionalities that was necesary to improve this section as change password and roles asign

**Comment by yeyo2k3** [comment]
Funtionalities in 80% are developed, Roles Asign is missing after review, this subsection was asigned to valentina but she was moved to AICCRA project and this was not finished properly, @gcmartinezg  will finish this functionlity to complete the issue

this is an Screenshoot to evidence the advance 
![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/8a70d7c2-7a86-4139-9579-65711e1eae24)

**Comment by gcmartinezg** [comment]
Finished the user role management dialog from the user admin panel by clicking the 4th button in the "Actions" column
![image.png](https://images.zenhubusercontent.com/5e41bc3bbbef8f1e84922988/1baadeff-07ea-4c4f-b760-9420483cfc11)

**Comment by yeyo2k3** [comment]
@gcmartinezg please if you consider if it is correct, please move this to dev environment and change the status to on review

**Comment by jdmunozg** [comment]
moves to in progress because you are working on new administrator functionalities

**Comment by jdmunozg** [comment]
It is added to deactivate and activate the user, in addition the bug of searching in the input is Cgiar is fixed.

**Comment by jdmunozg** [comment]
![chrome_eBWCh1SVPm](https://user-images.githubusercontent.com/72575589/173844023-5ca859fb-2361-4a61-b8b1-3a909b9c002e.png)
![chrome_HZsko3pdMZ](https://user-images.githubusercontent.com/72575589/173844283-044397cf-6b15-456a-b6cd-ef14924cfad5.png)
![chrome_pdC3m8g9ek](https://user-images.githubusercontent.com/72575589/173844330-5628754a-31ca-43a3-ad0b-6df173ba9715.png)
