### ISSUE TITLE
Create Roles Admin Panel

### ISSUE THREAD

**Issue by yeyo2k3** [AllianceBioversityCIAT/CLARISA-Legacy#22]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
As CLARISA user loged, I want manage roles for CLARISA Services so that I need to create a admin Panel to manage roles into CLARISA

Add Screenshot
-------------------------------------------------------------------------------

Tasks:
-------------------------------------------------------------------------------
- [x] Migration
- [x] Backend 
- [x] Frontend

Deliverable or Expected outcome:
-------------------------------------------------------------------------------
- [x] Service
- [x] Website or section

Additional comments: 
-------------------------------------------------------------------------------

**Comment by yeyo2k3** [comment]
We created a mockup [here ](https://docs.google.com/presentation/d/1Rh6oj_hBumR7LytLUsMa_jmDwSZaRWAOEA8pe7R4cxw/edit?usp=sharing), After aprovation of mockup, we developed a interface with all services with frontend components
![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/a8da37ec-8582-4fa6-8348-e2895ea9ebab)
after review the funtionality of this section, we proceed to close this issue

**Comment by gcmartinezg** [comment]
Reopening because the functionality to reactivate a role was not developed

**Comment by jdmunozg** [comment]
The table is divided into two tabs, to identify the deactivated and activated, in addition the functionality of activating the role is created

**Comment by jdmunozg** [comment]
![chrome_mU5HZzwlgX](https://user-images.githubusercontent.com/72575589/173850580-37896f21-a01d-49c1-a8f5-cee21d0bf1ee.png)
![chrome_BKCWyLmwT2](https://user-images.githubusercontent.com/72575589/173850599-be2a741f-1453-4f98-8667-18ff722d70b5.png)
![chrome_Ca56o24s2l](https://user-images.githubusercontent.com/72575589/173850623-a5dd0754-85aa-473a-b653-951f98c3ef94.png)
