### ISSUE TITLE
QA Process Batch 3

### ISSUE THREAD

**Issue by yeyo2k3** [AllianceBioversityCIAT/CLARISA-Legacy#28]
Provide support to RTB and FISH for Annual Report submission between MEL and CLARISA

We expected to recieved information from Fish
1. SLOs
2. Policies
3. OICRs
4. Innovations
5. Publications.
6. Capdev
7. External Partnertships (Optional)
8. MELIA

from RTB we expected to recieved information 
1. Publications.

**Comment by yeyo2k3** [comment]
we recieved a request from Cristiano Rossignoli to include FISH milestones
![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/49f5e6f1-5516-46b1-a532-bac105f516b7)

**Comment by yeyo2k3** [comment]
we created all milestones in CLARISA and share information to be exposed through CLARISA and he replied confirming the data.
![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/360b5006-5063-48c0-928c-fb8a2eb5bbe3)

**Comment by RodrigoOrtizM** [comment]
Can we close this issue? @yeyo2k3

**Comment by htobon** [comment]
IS this issue related only to RTB and FISH? If so, what about GLDC?

**Comment by yeyo2k3** [comment]
@htobon this issue was is related to RTB and FISH updates. GLDC was not part of Batch 3

@RodrigoOrtizM we can not close this issue yet, we have to wait to round 2 of QA with any expected update from FISH based on QA assesors comments, this will come at next until may 18th as tentative date

**Comment by yeyo2k3** [comment]
@gcmartinezg this data could be come on week between may 30th and June 1st

**Comment by gcmartinezg** [comment]
Nothing did happen for this last batch. Closing the issue.
