### ISSUE TITLE
Permission Admin Panel

### ISSUE THREAD

**Issue by yeyo2k3** [AllianceBioversityCIAT/CLARISA-Legacy#30]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
**As** [CLARISA admin user], **I want** [manage and asign permission to users to access APIs] **so that** [We need to create an admin panel to manage roles to API endpoints]

-------------------------------------------------------------------------------

**Comment by jdmunozg** [comment]
The problem was encountered as to because it was not cleaned when it was updated and it was given a solution

**Comment by jdmunozg** [comment]
![chrome_e6en0ibue5](https://user-images.githubusercontent.com/72575589/173834010-8cf45d21-ca4b-410f-923b-cb600fcf711d.gif)
