### ISSUE TITLE
CLARISA Auditlog for transactions

### ISSUE THREAD

**Issue by yeyo2k3** [AllianceBioversityCIAT/CLARISA-Legacy#34]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Develop and Documentation about register any change made using CLARISA standalone

-------------------------------------------------------------------------------

**Comment by gcmartinezg** [comment]
Started with [this commit](https://github.com/AllianceBioversityCIAT/CLARISA/commit/cd0393ec3e9eb3c5b174254125e50847d4259b01)

**Comment by gcmartinezg** [comment]
Functionality done for successful transactions. For failed requests, please see #50
