### ISSUE TITLE
Workpackages Duplicated data on service

### ISSUE THREAD

**Issue by yeyo2k3** [AllianceBioversityCIAT/CLARISA-Legacy#51]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
This issue refers a ticket #3253 that defined duplicated data at workpackages service 

Add Screenshot
-------------------------------------------------------------------------------
![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/5a1fe9c2-16e9-4744-8c58-be595793c9f4)
Tasks:
-------------------------------------------------------------------------------
- [x] Validation 
- [x] Resolve

Deliverable or Expected outcome:
-------------------------------------------------------------------------------
- [x] Service fixed

Additional comments: 
-------------------------------------------------------------------------------

**Comment by yeyo2k3** [comment]
we reviewed the service and noted that some fields have changed and the data is duplicated, we comunicate this to OST team, the result was  from OST team were resolved the duplicated data and in CLARISA we fix fields mapping and add an additional field called wp_official_code to avoid duplicated id. Now we can expose data from API properly

![image.png](https://images.zenhubusercontent.com/5d3718852c1c7b71d87abdf1/4ced5890-3483-40ad-b7f8-c409234879d7)

**Comment by yeyo2k3** [comment]
we will expect the lastest changes on OST production environment to obtain the complete functionality made by OST team on workpackages. Please @JuankCadavid let us know when this will be ready on OST prod

**Comment by gcmartinezg** [comment]
Modify/create service to show only workpackages from active initiatives and stage 4 (or the highest stage number)

**Comment by jdmunozg** [comment]
Waiting for Juan Carlos' information to finish

**Comment by jdmunozg** [comment]
The solution was reviewed and approved
