### ISSUE TITLE
Control lists not loading on CLARISA

### ISSUE THREAD

**Issue by gcmartinezg** [AllianceBioversityCIAT/CLARISA-Legacy#55]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
All the control lists are not loading when an user clicks the button to display the table. Upon checking the developer tools, we can see that the services can not be loaded because a 401 Unauthorized error is happening. We need to check why this error is happening and to solve the problem.

Add Screenshot
-------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/54682133/172703141-44b7e844-9b3c-45f2-b813-8f17f63e3c41.png)
The control lists keeps trying to get the information, but nothing happens

![image](https://user-images.githubusercontent.com/54682133/172703357-ac7b4709-a6f9-42e0-9bb9-261a7c6261af.png)
The error message being displayed in the browser's console

Tasks:
-------------------------------------------------------------------------------
- [x] Discover what is the problem
- [x] Fix the problem
- [x] Notify the users when the issue is solved

**Comment by jdmunozg** [comment]
We thought that the error came at the time of instancing the public user. Trying to solve this, we modified the position of the filters. When testing this solution, we realized that the public user did not have the appropriate permissions to fetch the data from the control list.

**Comment by gcmartinezg** [comment]
![image.png](https://images.zenhubusercontent.com/5e41bc3bbbef8f1e84922988/f4f53f09-da5c-4147-81ff-330e67fa45dd)
