### ISSUE TITLE
Active Directory [AD] Integration

### ISSUE THREAD

**Issue by juansebastianortega** [AllianceBioversityCIAT/CLARISA-Legacy#6]
Description:
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
**As** [CLARISA user], **I want** [to add a new institution througth CLARISA] **so that** [I can use this institution for mapping]

-------------------------------------------------------------------------------

### **Acceptance Criteria**

1. - [x] **Given** [a user into the institutions management module - clarisa website ]  , **when** [the user try to login to the module pressing login button], **then**, [The system identify the user with CGIAR active directory]
2. - [x] **Given** [a CLARISA user into the institutions management module - clarisa website ]  , **when** [The user try to login with a non-CGIAR mail], **then**, [The system will identify him with CLARISA user database]

**Comment by yeyo2k3** [comment]
Currently we removed the option to accept or reject request, meanwhile, this part  can be managed by others apps
